### PR TITLE
Improve .es domains

### PR DESCRIPTION
**Pull request by coriaweb**
I think that the logical thing is that the .es are adapted to the real use in Spain, the best method is that it is translated as I indicate below. It works for me and it is easier for Spanish clients.

### CODE REVIEW

**Comment by MrKoopie** [comment]
@coriaweb The language files are in English and translations should be located somewhere else. You can add to your custom language file the translations (as WHMCS intended to) since translating this in English would confuse non-spanish customers.

To translate the fields, check out https://docs.whmcs.com/Additional_Domain_Fields#How_do_I_customise_the_fields_that_are_displayed.3F -> Translating a Field Name. 

While checking out the language files, I noticed that esIdentificationType has a key but Número de identificación does not. Perhaps this is something for openprovider to fix in the next release @opmain ?

**Comment by coriaweb** [comment]
Okay, but the way it is currently built makes it very difficult to register a .es. I think it would be 100% useful to leave only 2 fields. CIF (for companies), DNI (for individuals).

With this form, they have never contacted us to know how to register a .es.

**Comment by MrKoopie** [comment]
@coriaweb There are three different fields. The problem is that only one of them is required, depending on the kind of identification. Since WHMS does not support conditional requirements, a change was made where the dropdown shows the identification option and only one field for the number is required.

I just compared your pull request against the current file. It looks like you have removed some fields, as originally it is this:

https://github.com/openprovider/OP-WHMCS7/blob/ce74977115c30c9d8482fe8e9c7ff3775e5e2a6f/modules/registrars/openprovider/configuration/additionalfields.php#L390-L397

I can see that the file already includes Spanish translations. Could you elaborate on why this does not work for you?

**Comment by coriaweb** [comment]
socialSecurityNumber|Número Seguridad Social (Social Security Number) <-- This is completely useless.

número de pasaporte | Pasaporte / DNI (Número de pasaporte)" <-- This gives greater importance to the passport, when the main document is the DNI, so it confuses Spanish customers.

The field of the CIF could be left as it is, this is no problem, I only specified the most useful form for the real requirements of Spain.

**Pull request merged**
